# Generated by Django 3.1.5 on 2021-03-01 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agegender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplemodel',
            name='model_pic',
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img/%y'),
            preserve_default=False,
        ),
    ]
